apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: full-endpoint
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: full-endpoint-pods
    spec:
      containers:
      - image: gcr.io/agmsb-appdev/full-endpoint:3.0
        name: full-endpoint-container
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http-server