apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: projects-endpoint
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: projects-endpoint-pods
    spec:
      containers:
      - image: gcr.io/agmsb-appdev/projects-endpoint:2.1
        name: projects-endpoint-container
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http-server